// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package loan is a generated GoMock package.
package loan

import (
	context "context"
	reflect "reflect"
	time "time"
	loan "weekly_loan_program/service/loan"

	gomock "github.com/golang/mock/gomock"
)

// MockLoanServiceProvider is a mock of LoanServiceProvider interface.
type MockLoanServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLoanServiceProviderMockRecorder
}

// MockLoanServiceProviderMockRecorder is the mock recorder for MockLoanServiceProvider.
type MockLoanServiceProviderMockRecorder struct {
	mock *MockLoanServiceProvider
}

// NewMockLoanServiceProvider creates a new mock instance.
func NewMockLoanServiceProvider(ctrl *gomock.Controller) *MockLoanServiceProvider {
	mock := &MockLoanServiceProvider{ctrl: ctrl}
	mock.recorder = &MockLoanServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanServiceProvider) EXPECT() *MockLoanServiceProviderMockRecorder {
	return m.recorder
}

// CreateLoanWithBilling mocks base method.
func (m *MockLoanServiceProvider) CreateLoanWithBilling(ctx context.Context, loan loan.Loan, billings []loan.Billing) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoanWithBilling", ctx, loan, billings)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoanWithBilling indicates an expected call of CreateLoanWithBilling.
func (mr *MockLoanServiceProviderMockRecorder) CreateLoanWithBilling(ctx, loan, billings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoanWithBilling", reflect.TypeOf((*MockLoanServiceProvider)(nil).CreateLoanWithBilling), ctx, loan, billings)
}

// GetBillingsByLoanIDAndDueDate mocks base method.
func (m *MockLoanServiceProvider) GetBillingsByLoanIDAndDueDate(ctx context.Context, loanID int64, dueDate time.Time, status int16) ([]loan.Billing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBillingsByLoanIDAndDueDate", ctx, loanID, dueDate, status)
	ret0, _ := ret[0].([]loan.Billing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBillingsByLoanIDAndDueDate indicates an expected call of GetBillingsByLoanIDAndDueDate.
func (mr *MockLoanServiceProviderMockRecorder) GetBillingsByLoanIDAndDueDate(ctx, loanID, dueDate, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBillingsByLoanIDAndDueDate", reflect.TypeOf((*MockLoanServiceProvider)(nil).GetBillingsByLoanIDAndDueDate), ctx, loanID, dueDate, status)
}

// GetLoansByStatusesAndLastActivityTime mocks base method.
func (m *MockLoanServiceProvider) GetLoansByStatusesAndLastActivityTime(ctx context.Context, statuses []int16, lastActivityDate time.Time) ([]loan.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoansByStatusesAndLastActivityTime", ctx, statuses, lastActivityDate)
	ret0, _ := ret[0].([]loan.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoansByStatusesAndLastActivityTime indicates an expected call of GetLoansByStatusesAndLastActivityTime.
func (mr *MockLoanServiceProviderMockRecorder) GetLoansByStatusesAndLastActivityTime(ctx, statuses, lastActivityDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoansByStatusesAndLastActivityTime", reflect.TypeOf((*MockLoanServiceProvider)(nil).GetLoansByStatusesAndLastActivityTime), ctx, statuses, lastActivityDate)
}

// GetUserLoansByUserID mocks base method.
func (m *MockLoanServiceProvider) GetUserLoansByUserID(ctx context.Context, userID int64) ([]loan.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLoansByUserID", ctx, userID)
	ret0, _ := ret[0].([]loan.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLoansByUserID indicates an expected call of GetUserLoansByUserID.
func (mr *MockLoanServiceProviderMockRecorder) GetUserLoansByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLoansByUserID", reflect.TypeOf((*MockLoanServiceProvider)(nil).GetUserLoansByUserID), ctx, userID)
}

// UpdateLoanByPayment mocks base method.
func (m *MockLoanServiceProvider) UpdateLoanByPayment(ctx context.Context, input loan.UpdateLoanByPaymentInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoanByPayment", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoanByPayment indicates an expected call of UpdateLoanByPayment.
func (mr *MockLoanServiceProviderMockRecorder) UpdateLoanByPayment(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoanByPayment", reflect.TypeOf((*MockLoanServiceProvider)(nil).UpdateLoanByPayment), ctx, input)
}

// UpdateLoansStatusAndUpdateTimeByIDs mocks base method.
func (m *MockLoanServiceProvider) UpdateLoansStatusAndUpdateTimeByIDs(ctx context.Context, loanIDs, userIDs []int64, status int16, updateTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoansStatusAndUpdateTimeByIDs", ctx, loanIDs, userIDs, status, updateTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoansStatusAndUpdateTimeByIDs indicates an expected call of UpdateLoansStatusAndUpdateTimeByIDs.
func (mr *MockLoanServiceProviderMockRecorder) UpdateLoansStatusAndUpdateTimeByIDs(ctx, loanIDs, userIDs, status, updateTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoansStatusAndUpdateTimeByIDs", reflect.TypeOf((*MockLoanServiceProvider)(nil).UpdateLoansStatusAndUpdateTimeByIDs), ctx, loanIDs, userIDs, status, updateTime)
}
